config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'main/index'
  get 'explanations/index'
  get 'reservations/search'
  root 'main#index'
  #devise_for :users
  resources :reservations do
    resources :participants, only: :create
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<!DOCTYPE html>
<html class="no-js" lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="stylesheet" href="./css/normalize.css">
<link rel="stylesheet" href="./css/main.css">
<script src="./js/vendor/modernizr.custom.min.js"></script>
<script src="./js/vendor/jquery-1.10.2.min.js"></script>
<script src="./js/main.js"></script>
</head>
<body>

<header class="hero-header">
  <div class="inner">
    <div class="slideshow">
      <img src="/assets/slide-1.jpg" alt="" width="1500" height="465">
      <img src="/assets/slide-2.jpg" alt="" width="1500" height="465">
      <img src="/assets/slide-3.jpg" alt="" width="1500" height="465">
      <img src="/assets/slide-4.jpg" alt="" width="1500" height="465">
    </div>
  </div>
</header>

</body>
</html>


<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="stylesheets" href="./normalize.css">
<link rel="stylesheets" href="./main.css">

<script src="./js/vendor/jquery-1.10.2.min.js"></script>
<script src="./js/vendor/jquery-ui-1.10.3.custom.min.js"></script>
<script src="main.js"></script>
</head>
<body>

<header class="page-header" role="banner">
    <h1>Let's play tennis</h1>
</header>

<div class="page-main" role="main">
  <aside>
    <ul>
      <div class="image_tag">
        <li><%= link_to image_tag("/assets/01_aside.png", width: '200'), explanations_index_path %></li>
      </div>
      <div class="image_tag">
        <li><%= link_to image_tag("/assets/02_aside.png", width: '200'), reservations_path %></li>
      </div>
      <div class="image_tag">
        <li><%= link_to image_tag("/assets/03_aside.png", width: '200'), new_reservation_path %></li>
      </div>
    </ul>
    <button><img src="/assets/btn_open.png"></button>
  </aside>
</div>

<!--footer class="page-footer" role="contentinfo"-->
    <!--small class="copyright">COPYRIGHT &copy; <a href="http://www.shiftbrain.co.jp" target="_blank">SHIFTBRAIN Inc.</a></small-->
<div class="low-text">
    手軽にテニスをしたい<br>
    <br>
</div>
<div class="low-text">
    今すぐテニスをしたい<br>
    <br>
</div>
<div class="low-text">
    仲間を見つけたい・・<br>
    <br><br>
</div>
<div class="low-low-text">
    さあ！今すぐテニスを始めましょう！！
</div>

<!--/footer-->

</body>
</html>