config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'main/index'
  get 'explanations/index'
  get 'reservations/search'
  root 'main#index'
  #devise_for :users
  resources :reservations do
    resources :participants, only: :create
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :participants
  belongs_to :city
  belongs_to :user
  has_many :comments

  validates :city_id, numericality: { other_than: 1 }
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :search_reservation, only: [:index, :search]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
    set_reservation_column
  end

  def search
    @results = @p.result.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    @participant = Participant.new
    #@participants = Participant.all
    @participants = @reservation.participants.all.order("created_at DESC")
    @comment = Comment.new
    @comments = @reservation.comments.all.order("created_at DESC")
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:start_time, :end_time, :min, :max, :level, :text, :area, :city_id).merge(user_id: current_user.id)
    end

    def move_to_index
      unless user_signed_in?
        redirect_to action: :index
      end
    end

    def search_reservation
      @p = Reservation.ransack(params[:q]) 
    end

    def set_reservation_column
      @reservation_area = Reservation.select("area").distinct
      @reservation_level = Reservation.select("level").distinct
      @reservation_start_time = Reservation.select("start_time").distinct
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :お名前 %>
    <%= current_user.nickname %>
  </div>

  <div class="field">
    <%= form.label :レベル %>
    <%= form.select :level, ['初級', "中級","上級"] %>
  </div>

  <div class="field">
    <%= form.label :地域 %>
    <%= form.collection_select(:city_id, City.all, :id, :name, {}, {class:"city-select"}) %>
  </div>

  <div class="field">
    <%= form.label :集合場所 %>
    <%= form.text_area :area %>
  </div>

  <div class="field">
    <%= form.label :集合時間 %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :解散時間 %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :最低参加人数　何人から？ %>
    <%= form.select :min, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'] %>
  </div>

  <div class="field">
    <%= form.label :最高参加人数　何人まで？ %>
    <%= form.select :max, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'] %>
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit :登録 %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<header class="header">
  <h1 class="header_bar">
    <%= link_to root_path, data: {"turbolinks" => false} do %><%= image_tag "ball.png" %>  TENNIS<% end %>
  </h1>
  <nav class="pc-nav">
    <ul class="nav_bar">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path, class: "post" %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: "post" %></li>
        <li><%= link_to 'Log in for TEST', users_guest_sign_in_path, method: :post %></li>
      <% end %>
    </ul>
  </nav>
</header>

<div class="title">イベント検索</div>
<%= search_form_for @p, url: reservations_search_path do |f| %>
  <%= f.label :area_eq, '場所' %>
  <%= f.collection_select :area_eq, @reservation_area, :area, :area, include_blank: '指定なし' %>
  <br>
  <%= f.label :level_eq, 'レベル' %>
  <%= f.collection_select :level_eq, @reservation_level, :level, :level, include_blank: '指定なし' %>
  <br>
  <%= f.label :start_time_eq, '日時' %>
  <%= f.collection_select :start_time_eq, @reservation_start_time, :start_time, :start_time, include_blank: '指定なし' %>
  <br>
  <%= f.submit '検索' %>
<% end %>

<div class="title">イベント一覧</div>

<table>
  <thead>
    <tr>
      <th>地域</th>
      <th>レベル</th>
      <th>日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.city.name %></td>
        <td><%= reservation.level %></td>
        <td><%= reservation.start_time.strftime("%Y-%m-%d %H:%M") %>〜</td>
        <td><%= link_to '[詳細＆参加申込]', reservation %></td>
        <% if user_signed_in? && current_user.id == reservation.user_id %>
          <td><%= link_to '[編集]', edit_reservation_path(reservation) %></td>
          <td><%= link_to '[削除]', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= month_calendar events: @reservations do |date, reservations| %>
  <%= date %>

  <% reservations.each do |reservation| %>
    <div>
      <%= reservation.start_time.strftime("%H:%M") %>
      <%= link_to reservation.city.name, reservation %>
    </div>
  <% end %>
<% end %>

<br>
<% if user_signed_in? %>
  <%= link_to '[イベント登録]', new_reservation_path %>
<% else %>
  <strong>※※※イベントの登録には新規登録/ログインが必要です※※※</strong>
<% end %>

app/views/reservations/new.html.erb
<div class="devise_img">

<h1 class="devise">イベント登録</h1>
<div class="devise_box">
<div class="event_border">
<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

</div>
</div>
</div>

app/views/reservations/search.html.erb
<div class="devise_img">
<h1>
  <br>検索結果
</h1>
<% if @results.length !=0 %>
  <% @results.each do |result| %>
    <td>
    <br>
    <li>
      <%= result.level %>
      <%= result.start_time %>
      <%= result.end_time %>
      <%= result.city_id %>
    </li>
  <% end %>
<% else %>
  該当するイベントはありません
<% end %>
<br>
<div class="search">
  <%= link_to 'カレンダーから予約する', reservations_path %><br><br>
</div>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="devise_img">
  <div class="devise_box">
    <div class="event_border">
      <div class="event_field">
        <strong>イベント登録者名:</strong>
        <%= @reservation.user.nickname %>
      </div><br>

      <div class="event_field">
        <strong>レベル:</strong>
        <%= @reservation.level %>
      </div><br>

      <div class="event_field">
        <strong>地域:</strong>
        <%= @reservation.city.name %>
      </div><br>

      <div class="event_field">
        <strong>場所:</strong>
        <%= @reservation.area %>
      </div><br>

      <div class="event_field">
        <strong>集合時間:</strong>
        <%= @reservation.start_time.strftime("%Y-%m-%d %H:%M") %>
      </div><br>

      <div class="event_field">
        <strong>解散時間:</strong>
        <%= @reservation.end_time.strftime("%Y-%m-%d %H:%M") %>
      </div><br>

      <div class="event_field">
        <strong>最低参加人数:</strong>
        <%= @reservation.min %>
        ＊人数が足りない場合はキャンセルの場合があります
      </div><br>

      <div class="event_field">
        <strong>最大参加人数:</strong>
        <%= @reservation.max %>
      </div><br>

      <div class="event_field">
        <strong>備考:</strong>
        <%= @reservation.text %>
      </div><br>
    </div>
  </div>



  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@reservation, @participant], local: true) do |form| %>
        <%= form.text_field :text, placeholder: "参加するにあたり一言" %>
        <%= form.submit "参加する" %>
      <% end %>
    <% else %>
      <strong><p>※※※ 参加するには新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="participants">
      <h4>＜参加者一覧＞</h4>
      <% @participants.each do |participant| %>
        <p>
          <strong><%= participant.user.nickname %>：<%= participant.text %></strong>
        </p>
      <% end %>
    </div>
  </div>




  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@reservation, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.nickname %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>